### ISSUE TITLE
Remove getValue from all enums

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-java#101]
Numeric value of enum is actually not needed outside of roc-java package.

* remove `getValue` method from all enums
* convert `value` field of all enums from private to package-private
* use `value` instead of `getValue` everywhere inside roc-java

**Comment by PoulasthaMukherjee** [comment]
@gavv Assign this to me

**Comment by PoulasthaMukherjee** [comment]
@gavv Assign this to me

**Comment by gavv** [comment]
@PoulasthaMukherjee welcome

**Comment by PoulasthaMukherjee** [comment]
@gavv Thank you. I'll get it ready by tomorrow.

**Comment by PoulasthaMukherjee** [comment]
@gavv Can you check my PR and merge it?

**Comment by gavv** [comment]
Shouldn't it be `gsoc23` instead of `gssoc23`?

**Comment by gavv** [comment]
@PoulasthaMukherjee Could you reference any document describing those gsoc labels and their meaning?

**Comment by PoulasthaMukherjee** [comment]
Actually it's GirlScript Summer of Code

**Comment by PoulasthaMukherjee** [comment]
Not Google Summer of Code

**Comment by gavv** [comment]
@PoulasthaMukherjee Oh, I see. Nevertheless, the question is still relevant - please provide any links describing this github label and why and when is it needed. Can't find anything about labels in google, unfortunately.
