### ISSUE TITLE
Add validation for unsigned integer fields in configs

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-java#104]
RocContextConfig, RocSenderConfig, RocReceiverConfig have some fields that have int or long types, but actually are not allowed to be negative.

If the user tries to make them negative, they'll get error when opening context, sender, and receiver.

It would be more convenient to catch these errors earlier - immediately when trying to set negative value to config. We already provide type checking for other values - e.g. enums are checked by compiler.

Fields to be checked to be `>= 0`:

* RocContextConfig

  * maxPacketSize
  * maxFrameSize

* RocSenderConfig

  * frameSampleRate
  * packetSampleRate
  * fecBlockSourcePackets
  * fecBlockRepairPackets

* RocReceiverConfig

  * frameSampleRate

I think we should add a new method to `Check` class and invoke this method in setters and builder methods for corresponding fields.

**Comment by DieMass** [comment]
Hi, @gavv ! It seems to me that we have the opportunity not to add a check for a negative number in the builder, if such a check is in the constructor. In this case, the changes I proposed can be accepted.

**Comment by gavv** [comment]
@DieMass thanks for PR!

> It seems to me that we have the opportunity not to add a check for a negative number in the builder, if such a check is in the constructor.

@ortex WDYT?

**Comment by ortex** [comment]
I agree, we could skip check in the builder
