### ISSUE TITLE
Document version requirements and guidelines

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-java#106]
Here are some things we need to document in README.

**For user - what are requirements**

* For desktop - range of supported JDK versions needed when building the project from sources.

* Minimum Java version (build and run-time) - what is it and where it is defined.

  * https://github.com/roc-streaming/roc-java/blob/b3096658ed7c7f34e42272d51d6d39f5bb38646c/build.gradle#L18-L19
  * https://github.com/roc-streaming/roc-java/blob/b3096658ed7c7f34e42272d51d6d39f5bb38646c/android/roc-android/build.gradle#L41-L42

* Minimum Android version - what is level, what is corresponding OS version, and where it is defined.

  * https://github.com/roc-streaming/roc-java/blob/b3096658ed7c7f34e42272d51d6d39f5bb38646c/android/roc-android/build.gradle#L26

**For developer - what versions to bump**

roc-java developers should periodically bump the following versions to the latest available: 

* SDK API level (SDK_LEVEL) (sets compileSdkVersion and targetSdkVersion)
* Android NDK version (NDK_VERSION)
* Android build-tools version (BUILD_TOOLS_VERSION)
* CMake version (CMAKE_VERSION)

All these versions are defined in `build.yml` as described in detail in this issue: #105. We can include some info and links from that issue to README.

See also #112. ROC_VERSION will also need periodical bump.

I think we should also mention `android_docker.sh`, which has its own set of defaults. These defaults are used if the user did not specify any variables when building AAR locally.

**Comment by PoulasthaMukherjee** [comment]
@gavv May I work on this?

**Comment by gavv** [comment]
@PoulasthaMukherjee Hi,

This is not actually a [help wanted](https://github.com/roc-streaming/roc-java/labels/help%20wanted) task, but if you feel confident about what should be done here, the help is appreciated! 

Otherwise, you're welcome to check out other tasks, and thanks for your interest

**Comment by gavv** [comment]
Fixed via #132, docs added to README.
