### ISSUE TITLE
Use Duration class instead of long for time values in configs

### ISSUE THREAD

**Issue by ortex** [roc-streaming/roc-java#111]
Find all fields in RocSenderConfig and RocReceiverConfig that hold durations (in nanoseconds), e.g. `targetLatency`, and convert them from `long` to `Duration`. Adjust JNI side accordingly.

Fields of interest:

SenderConfig:
 - [x] PacketLength

ReceiverConfig
 - [x] TargetLatency
 - [x] MaxLatencyOverrun
 - [x] MaxLatencyUnderrun
 - [x] NoPlaybackTimeout
 - [x] BrokenPlaybackTimeout
 - [x] BreakageDetectionWindow

**Comment by ortex** [comment]
Need to edit existing one, e.g. https://github.com/roc-streaming/roc-java/blob/21342c2325582c960c5980f94603d1c00c9e8247/roc_jni/src/main/impl/receiver.c#L57-L60

machine generated - it's only header files, no need to touch them in this task

**Comment by gavv** [comment]
Unfinished PR: #122
