### ISSUE TITLE
Whether to support multicast

### ISSUE THREAD

**Issue by chenqinggang001** [roc-streaming/roc-java#129]
Is it okay to do that?
Sender ：
new Endpoint("rtp+rs8m://239.244.0.100:10001");
Receiver ：
new Endpoint("rtp+rs8m://239.244.0.100:10001");

**Comment by chenqinggang001** [comment]
Thank you ！
I still want to ask another question，Is it possible to support video transmission? Is the workload heavy?

**Comment by gavv** [comment]
Video is not supported yet, but yes, it's planned, and we're slowly preparing internals to that. What do you mean by heavy workload?

**Comment by gavv** [comment]
Feel free to reopen if needed.
