### ISSUE TITLE
Indicates whether there is a multicast example

### ISSUE THREAD

**Issue by chenqinggang001** [roc-streaming/roc-java#131]
I only saw unicast examples in the document, is there any example related to multicast for reference？
https://roc-streaming.org/toolkit/docs/manuals/roc_send.html

**Comment by gavv** [comment]
Hi,

For multicast you need two things:

- use multicast interface for endpoints (like 224.0.0.1)
- either tell roc to join multicast group, or join it by yourself

If you're asking specifically about CLI tools (you gave a link to `roc-send` tool), then take a look at `--miface` option. (`roc-recv` has it for a long time, but `roc-send` has it only in develop branch; for `roc-send` it's needed when using RTCP).

In C API, see `roc_interface_config`. It allows to specify multicast group which you want to join.

In Java bindings, I think it's not covered yet, so you'll have to join multicast group manually using platform-specific APIs before binding/connecting endpoints.
