### ISSUE TITLE
Java package rename

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-java#22]
As recently posted to the mailing list, I've renamed github org to "roc-streaming" and also renamed the main repo from just "roc" to "roc-toolkit".

So the full name of this roc-java project is now something like "JNI bindings to Roc Toolkit".

I've also registered a domain name, finally: https://roc-streaming.org/

"Roc Toolkit" is considered as a "sub-project" of the Roc Streaming organization.

So now I suggest to rename Java package from `com.github.rocproject.roc` to something based on the new domain, e.g.:

* `org.rocstreaming.roc`
* `org.rocstreaming.roctoolkit`
* `org.rocstreaming.rocjava`
* etc

@MatteoArella @ortex Thoughts?

**Comment by ortex** [comment]
> So now I suggest to rename Java package from `com.github.rocproject.roc` to something based on the new domain, e.g.:
> 
> * `org.rocstreaming.roc`
> * `org.rocstreaming.roctoolkit`
> * `org.rocstreaming.rocjava`
> * etc

To be honest, these variants look almost the same for me :)
But, since it is bindings for Roc Toolkit I guess it makes sense to choose `org.rocstreaming.roctoolkit`

**Comment by MatteoArella** [comment]
In my opinion  `org.rocstreaming.roc` or `org.rocstreaming.roctoolkit` looks both good :+1:

**Comment by gavv** [comment]
Great, let's go with `org.rocstreaming.roctoolkit`.
