### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-java#8]
Add travis build:

- [ ] Build and install libroc
- [ ] Build and install java bindings
- [ ] Run tests

Platforms:

- [ ] Linux
- [ ] macOS
- [ ] Android

See roc-go bindings: https://github.com/roc-project/roc-go/blob/master/.travis.yml

**Comment by gavv** [comment]
@MatteoArella can we close this?

**Comment by MatteoArella** [comment]
> @MatteoArella can we close this?

Yes
