### ISSUE TITLE
Build and publish HTML docs

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-java#9]
Automatically build and publish javadoc documentation.

Should be done after #10. For Maven Central and JCenter, there is https://www.javadoc.io/. For https://jitpack.io/ there is built-in javadoc support.

**Comment by gavv** [comment]
See also #10. For Maven Central and JCenter, there is https://www.javadoc.io/. For https://jitpack.io/ there is built-in javadoc support.

**Comment by ortex** [comment]
After publishing aar to maven central documentation available on javadoc.io https://javadoc.io/doc/org.roc-streaming.roctoolkit/roc-android/latest/index.html

For jar it also would be working since we going to publish jar on maven central as well
